### ISSUE TITLE
Basic docs

### ISSUE THREAD

**Issue by srinituraga** [TuragaLab/chromatix#11]
A few urgent doc requests. The urgency is because we would like new people to join the project, and it doesn't inspire a lot of confidence if these basic things don't exist.

- [x] Expand README.md. It currently looks like a not fully baked project because it doesn't have a lot of content. But we actually have a lot of material in readthedocs which should be replicated here. At the minimum, we should say what the project is, what capabilities it plans to have, install instructions, contributor list.

- [x] We need a prominent link back from readthedocs to the github page, probably at the top of all the pages, or at least the main page.

- [x] Right now, the docs link on the main github page is not really prominent because because it's in the top right corner. This should also be linked at the top of the README as a badge.

**Comment by diptodip** [comment]
Fixed by 27017018c82a011d33394010a3c35c6ca86a11c6, 36fd8549120cbbf4dfc6941523e0ce1d733d53c0, and b0acbd2482de5d646c100cb8ac808fea8dae13c3.
