### ISSUE TITLE
Run time error for examples

### ISSUE THREAD

**Issue by gschlafly** [TuragaLab/chromatix#18]
The holoscope.py and parallel_imaging.py examples run well. However, the parallel-imaging.py example fails to run with the following error message:

> jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.fft' failed: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/fft_thunk.cc:143) fft_plan != nullptr Failed to create cuFFT batched plan with scratch allocator.

The example script was run with the following command:
> assign-gpu -n 4 python examples/parallel_imaging.py

**Comment by diptodip** [comment]
I've added some variables to change the number of devices these programs use --- could you try it again and make sure it works on your computer (in the morning)?

**Comment by gschlafly** [comment]
Still causing the same error :(

**Comment by diptodip** [comment]
Even if you change the num_devices to 1?

**Comment by GJBoth** [comment]
@diptodip Did you fix this?

**Comment by diptodip** [comment]
This error doesn't happen on our machines, and the holoscope.py example has been updated a lot since then. Might be something to do with CUDA/cuDNN versions?

**Comment by GJBoth** [comment]
Alright, so closing due to probably some user machine error.
