### ISSUE TITLE
Input arguments for multi-wavelength field creation

### ISSUE THREAD

**Issue by guanghanmeng** [TuragaLab/chromatix#32]
Clarification needed for the following requirement: 
dx, spectrum, and spectral_density all need to be jnp arrays of the same dimension.

**Comment by GJBoth** [comment]
@diptodip Let's adress this too in #81 .

**Comment by diptodip** [comment]
Yup already on it

**Comment by diptodip** [comment]
Closed by PR https://github.com/TuragaLab/chromatix/pull/81
