### ISSUE TITLE
Fresnel transfer propagate phase calculation

### ISSUE THREAD

**Issue by nicolexi** [TuragaLab/chromatix#37]
In Goodman's book, for the Fresnel transfer function approach, the function is written as follows:
$$U(x,y,z) = \mathscr{F}^{-1}[\mathscr{F}(U(x,y,0))e^{jkz}exp(-j\pi\lambda z(f_x^2+f_y^2))]$$
In the propagation model in chromatix, we only have the phase part, which is $$U(x,y,z) = \mathscr{F}^{-1}[\mathscr{F}(U(x,y,0))exp(-j\pi\lambda z(f_x^2+f_y^2))]$$
Are we ignoring the z component for the scalar case? For the vectorial case, we might need to modify that.

**Comment by diptodip** [comment]
I think it's because that missing phase is constant across the field, so it shouldn't affect the result.

**Comment by gschlafly** [comment]
Propagation phase factor of exp(jkz) is omitted to improve the computation efficiency. This factor does not affect the intensity or the relative phase within the field. Only the absolute phase of the field is affected. I made a comment in the function in PR #42.

**Comment by GJBoth** [comment]
Closed by #42 !
