### ISSUE TITLE
Fix mkdocstrings-jupyter dependency

### ISSUE THREAD

**Issue by GJBoth** [TuragaLab/chromatix#4]
To locally build the docs, we need mkdocs-jupyter. However, it's version-incompatible with mkdocs-material so poetry can't add it. Not a major priority to fix, as readthedocs does everything well, but we should think about how to handle this...

**Comment by diptodip** [comment]
Could we not just ditch mkdocs-material?

**Comment by GJBoth** [comment]
That would imply changing the theme... I kinda like mkdocs-material, what alternative do you have in mind?

**Comment by diptodip** [comment]
How about the default readthedocs theme? Or the GitBook theme? I don't think the docs need to have a special theme :shrug:

**Comment by GJBoth** [comment]
Sure, or jupyterbook? It's what Jax uses and looks pretty sweet. WDYT?

**Comment by GJBoth** [comment]
Yeah it's sphinx based, so would require as well to redo the API, well, everything basically...

**Comment by diptodip** [comment]
I think it's worth it if we lose a dependency, but low priority.
