### ISSUE TITLE
Field property getter and setters

### ISSUE THREAD

**Issue by hosseybposh** [TuragaLab/chromatix#40]
At the moment field phase and intensity are defined as properties. It's very helpful and common to have property setters but you only have getters. 

The `replace` method requires you to reconstruct the entire `field.u` and often times in holography and displays you want to keep either phase or amplitude and replace the other. Property setters will make the code much more clean.

**Comment by GJBoth** [comment]
Property setters aren't allowed since everything is functional and the dataclass is frozen - so we can't do anything with this.
