### ISSUE TITLE
Setting trainable parameter

### ISSUE THREAD

**Issue by GJBoth** [TuragaLab/chromatix#7]
Our current approach for deciding if a parameter is trainable is to make it a function:

```
element(field, a=lambda key: 1.0, b=2.0) # a is trainable, b isn't
```

After discussing with @srinituraga, I'm agreeing with him this isn't very user friendly. The best alternative is probably having an additional `trainable` keyword, which sets which inputs are trained:

```
element(field, a=1.0, b=2.0, trainable=["a"])# a is trainable, b isn't
```

This seems the most compact and friendly option. Before I'll start implementing this, @diptodip @srinituraga WDYT?

**Comment by srinituraga** [comment]
I like this. But before we decide on a convention, can we see if there's any already established conventions for other jax libraries?

**Comment by diptodip** [comment]
I did enjoy the fact that I didn't have to type the parameters out twice, though on the other hand I have to type out a lambda each time I want to make something trainable. The closest analogy to the new style I can think of is what Jax does to decide which arguments are static, but that's a function wrapper, which isn't really the same thing.

Another approach might be to add a `Parameter` or `Trainable` wrapper class (which just holds a `jnp.ndarray`), which would look like:

```python
e = Element(a=Trainable(1.0), b=2.0) # a is trainable, b isn't
```

**Comment by srinituraga** [comment]
Oh I really like this Trainable() wrapper!


On Feb 14, 2023, at 2:52 PM, Diptodip ***@***.***> wrote:

External Email: Use Caution




I did enjoy the fact that I didn't have to type the parameters out twice, though on the other hand I have to type out a lambda each time I want to make something trainable. The closest analogy to the new style I can think of is what Jax does to decide which arguments are static, but that's a function wrapper, which isn't really the same thing.

Another approach might be to add a Parameter or Trainable wrapper class (which just holds a jnp.ndarray), which would look like:

e = Element(a=Trainable(1.0), b=2.0) # a is trainable, b isn't

**Comment by GJBoth** [comment]
I'm not a big fan of the `Trainable` wrapper - it introduces another datatype... And I worry about copying data by using the wrapper?

**Comment by GJBoth** [comment]
> But before we decide on a convention, can we see if there's any already established conventions for other jax libraries?

I haven't seen anything - usually because it's pretty clear what you want to optimize...

**Comment by diptodip** [comment]
Yeah, there is also `jax.grad` which has the `argnums` argument to decide what it differentiates with respect to, but again that's a function wrapper. For neural network layers, most of the time if something is optional (like a bias), there is an explicit boolean argument about whether to include that parameter or not. That doesn't really seem to be ideal for what we want to do here. 

Anyway, I don't really think there's a "Jax-y" precedent for this that I like/really applies here. I am also not a fan of checking strings, despite how common it is in Python :stuck_out_tongue:. But what's the problem with adding a type here?

**Comment by diptodip** [comment]
If we prefer functions for aesthetic reasons, it could be a function that looks like this:
```python
def trainable(x: Any) -> Callable:
    def init_fn(key: KeyArray) -> Any:
        return x
    return init_fn
```
so that the example looks like this:
```python
e = Element(a=trainable(1.0), b=2.0) # a is trainable, b isn't
```
And then we shouldn't need to update the elements themselves, which is nice.

**Comment by srinituraga** [comment]
I also like this!
